apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ixs6osp3y-python
  janus-idp.io/tekton: ixs6osp3y-python
  backstage.io/kubernetes-id: ixs6osp3y-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ixs6osp3y-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
